name: Continuous Integration

on:
  push:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: full
  THEGRAPH_STORE_POSTGRES_DIESEL_URL: "postgresql://postgres:postgres@localhost:5432/graph_node_test"

jobs:
  integration-tests:
    name: Run integration tests
    runs-on: ubuntu-latest
    timeout-minutes: 60
    env:
      RUSTFLAGS: "-C link-arg=-fuse-ld=lld -D warnings"
    steps:
      - name: Tune GitHub hosted runner to reduce flakiness
        # https://github.com/smorimoto/tune-github-hosted-runner-network/blob/main/action.yml
        run: sudo ethtool -K eth0 tx off rx off
      - name: Checkout sources
        uses: actions/checkout@v2
      - uses: Swatinem/rust-cache@v2

      - name: Install Node 16
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: yarn
          cache-dependency-path: "tests/integration-tests/yarn.lock"

      - name: Install lld and jq
        run: sudo apt-get install -y lld jq protobuf-compiler

      - name: Build graph-node
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --bin graph-node

      # Integration tests are a bit flaky, running them twice increases the
      # chances of one run succeeding.
      - name: Run integration tests (round 1)
        id: integration-tests-1
        uses: actions-rs/cargo@v1
        env:
          N_CONCURRENT_TESTS: "4"
          TESTS_GANACHE_HARD_WAIT_SECONDS: "30"
          ACCOUNTS: ${{ env.ACCOUNTS }}
          # Reduce how long a batch will stick around to avoid timeouts
          GRAPH_STORE_WRITE_BATCH_DURATION: 30
        with:
          command: neon
          args: --verbose --package graph-tests parallel_integration_tests -- --nocapture
        continue-on-error: true
      - name: Run integration tests (round 2)
        id: integration-tests-2
        uses: actions-rs/cargo@v1
        if: ${{ steps.integration-tests-1.outcome == 'failure' }}
        env:
          N_CONCURRENT_TESTS: "4"
          TESTS_GANACHE_HARD_WAIT_SECONDS: "30"
          # Reduce how long a batch will stick around to avoid timeouts
          GRAPH_STORE_WRITE_BATCH_DURATION: 30
        with:
          command: neon
          args: --verbose --package graph-tests parallel_integration_tests -- --nocapture