name: Run the graph tests

on:
  workflow_dispatch:
    inputs:
      distinct_id:
      accounts:

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: full

jobs:
  integration-tests:
    name: Run integration tests
    runs-on: ubuntu-latest
    timeout-minutes: 90
    env:
      RUSTFLAGS: "-C link-arg=-fuse-ld=lld -D warnings"
    steps:
      - name: echo distinct ID
        run: |
          echo distinct ID: ${{ github.event.inputs.distinct_id }}
          echo run ID: ${{ github.run_id }}
      - name: Tune GitHub hosted runner to reduce flakiness
        # https://github.com/smorimoto/tune-github-hosted-runner-network/blob/main/action.yml
        run: sudo ethtool -K eth0 tx off rx off
      - name: Checkout sources
        uses: actions/checkout@v2
      - uses: Swatinem/rust-cache@v2

      - name: Install Node 16
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: yarn
          cache-dependency-path: "tests/integration-tests/yarn.lock"

      - name: Install lld and jq
        run: sudo apt-get install -y lld jq protobuf-compiler

      - name: Run integration tests
        uses: actions-rs/cargo@v1
        env:
          N_CONCURRENT_TESTS: "1"
          TESTS_GANACHE_HARD_WAIT_SECONDS: "30"
          NEON_ACCOUNTS: ${{ github.event.inputs.accounts }}
          SUBGRAPH_NAME: ${{ github.run_id }}
          IPFS_URI: "https://ch-ipfs.neontest.xyz"
          GRAPH_NODE_ADMIN_URI: "https://ch2-graph.neontest.xyz/deploy/"
          # Reduce how long a batch will stick around to avoid timeouts
          GRAPH_STORE_WRITE_BATCH_DURATION: 30
        with:
          command: test
          args: --verbose --package graph-tests parallel_integration_tests -- --nocapture
